### ISSUE TITLE
Deck name character limit isn't checked when importing decks

### ISSUE THREAD

**Issue by ArkWist** [gumbyscout/fireemblem-cipher-utils#8]
I was building the official starter decks, as I considered they should perhaps be easily available somewhere. But when naming the first deck, "Starter Deck 1: War of Darkness", I was disappointed to see there is a 30 character limit to deck names.

Because the character limit seemed arbitrary, I tried editing it manually. I exported the deck and opened the resulting `fecudk` file. I changed the `name` field from "Starter Deck 1" to "Starter Deck 1: War of Darkness". I then reimported the deck.

The deck seemed to import without any problems. I could swap the deck in and out. I could add and remove cards. I could even save changes to the main character. The only problem was, if I tried to edit the deck name, I could not save a new (or the same) deck name greater than 30 characters long.

I can think of two solutions:

1. Increase (or remove) the deck name character limit. If the limit is indeed arbitrary, I think it should be greater than 30 characters.

2. Perform deck name sanitization when importing decks. If there are potential risks to increasing the character limit, then decks with names longer than the allowed length should be rejected or their names truncated.

**Comment by gumbyscout** [comment]
The deck name length is 100% arbitrary, it was actually put at @ZaFwamingDwagon 's suggestion to keep me from having to truncate deck names in the drawer. As I never cared if a user manually edited a deck file, and editing the deck file would result in no app breaking issues since strings are by default sanitized in react, I didn't think to clean decks on import.

Any suggestions @ZaFwamingDwagon ?

PS: Except for the newest Roy deck, all the other decks I had already put together and linked in the forum post, I guess I should probably link to them on the github page itself too. Here's the link if you are curious https://drive.google.com/folderview?id=0B1sqS5ok8pcDeWc5NG5BeUJXOEU&usp=sharing

**Comment by ArkWist** [comment]
Ah, somehow I missed that you'd already made the decks. Thanks for re-sharing the link.

**Comment by ZaFwamingDwagon** [comment]
We can remove the limit. Visually, I suppose we should implement truncation in the deck drawer if we do so. We might have to investigate in sanitation as suggested eventually.

**Comment by gumbyscout** [comment]
There isn't really any more sanitation to be done. This isn't a website where someone would actually put effort into somehow injecting code to steal personal data. This is a self contained app. Even if somehow they bypassed the sanitation that happens when JSON is parsed, and then the sanitation that happens when react displays a string, it's their own fault and it only affects them. Like, the source code is out there, there'd be no reason for them to try to inject code in an app where they can simply edit the source code.

If anything, we can make sure the app doesn't throw a fit if they make a deck without a name by hand, or if they have invalid ID's by hand for the cards in a deck.

**Comment by gumbyscout** [comment]
This should be fixed in v0.9.0
